-- AlterTable
ALTER TABLE "Test" ALTER COLUMN "bountyAmount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fee" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "totalFee" SET DATA TYPE DOUBLE PRECISION;
